openapi: 3.0.0
info:
  title: News Scraper API
  description: An API to manage and scrape news sources for headlines.
  version: 1.0.0


components:
  schemas:
    NewsSource:
      type: object
      properties:
        name:
          type: string
          description: Name of the news source
        url:
          type: string
          format: uri
          description: URL of the news source
    Headline:
      type: object
      properties:
        title:
          type: string
          description: Title of the headline
        source:
          type: string
          description: Name of the news source
        published-date:
          type: string
          format: date-time
          description: Date and time when the headline was published
        summary:
          type: string
          description: Summary of the headline
          maxLength: 500
    404Error:
      type: object
      properties:
        message:
          type: string
          description: No news found
        code:
          type: integer
          description: HTTP status code for the error
          example: 404


paths:
  /news_sources:
    get:
      summary: Get all news sources
      description: Retrieve a list of all available news sources.
      responses:
        '200':
          description: A list of news sources
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewsSource'    


  /news_sources/{name}:
    get:
      summary: Get a specific news source
      description: Retrieve details of a specific news source by name.
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: Name of the news source to retrieve
      responses:
        '200':
          description: Details of the specified news source
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsSource'


  /headlines:
    get:
      summary: Get headlines from all news sources
      description: Retrieve the latest headlines from all news sources.
      responses:
        '200':
          description: A list of headlines
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Headline'
        '404':
          description: No news found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'


  /headlines/{source}:
    get:
      summary: Get headlines from a specific news source
      description: Retrieve the latest headlines from a specific news source.
      parameters:
        - name: source
          in: path
          required: true
          schema:
            type: string
          description: Name of the news source to retrieve headlines from
      responses:
        '200':
          description: A list of headlines from the specified news source
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Headline'
        '404':
          description: No news found for the specified source
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'
  

  /headlines/{source}/first:
    get:
      summary: Get the first headline from a specific news source
      description: Retrieve the first headline from a specific news source.
      parameters:
        - name: source
          in: path
          required: true
          schema:
            type: string
          description: Name of the news source to retrieve the first headline from
      responses:
        '200':
          description: The first headline from the specified news source
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Headline'
        '404':
          description: No news found for the specified source
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'


  /search:
    get:
      summary: Search for headlines
      description: Search for headlines across all news sources based on a query.
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
          description: Search query to find headlines
      responses:
        '200':
          description: A list of headlines matching the search query
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Headline'
        '404':
          description: No news found matching the search query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'


  /search/{source}:
    get:
      summary: Search for headlines in a specific news source
      description: Search for headlines in a specific news source based on a query.
      parameters:
        - name: source
          in: path
          required: true
          schema:
            type: string
          description: Name of the news source to search headlines in
        - name: query
          in: query
          required: true
          schema:
            type: string
          description: Search query to find headlines
      responses:
        '200':
          description: A list of headlines matching the search query from the specified news source
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Headline'
        '404':
          description: No news found matching the search query for the specified source
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'


  /sort/{date}:
    get:
      summary: Sort headlines by date
      description: Retrieve headlines sorted by date.
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date-time
          description: Date to sort headlines by
      responses:
        '200':
          description: A list of headlines sorted by the specified date
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Headline'
        '404':
          description: No news to sort
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/404Error'



  